// PlusSamples.idl : IDL source for PlusSamples
//

// This file will be processed by the MIDL tool to
// produce the type library (PlusSamples.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(95ED38CC-DE67-4475-8AC7-828E47124F93),
	version(1.0),
	helpstring("PlusSamples 1.0 Type Library")
]
library PlusSamplesLib
{
	importlib("stdole2.tlb");
};
